function a2plots(u1,u,x,dx)
%a2plots plots an eigenfunction analysis in the case of a=2 (harmonic
%oscillator. We know the exact solutions to the problem so we can compute
%some numerical error exstimation. 

    subplot(2,3,1)
    plot(x,abs(u(:,1)-sqrt(dx)*exp(-x.^2/sqrt(2))*(sqrt(2)/pi)^(1/4)))
    legend('n=0')
    xlabel('x')
    ylabel('|u_{n}-\psi_{n}|')
    disp('norm of the 1st computed and analytical eigenfunction')
    norm(abs(u(:,1)-sqrt(dx)*exp(-x.^2/sqrt(2))*(sqrt(2)/pi)^(1/4)))
    subplot(2,3,2)
    plot(x,abs(u(:,2)+sqrt(dx)*hermiteH(1,(2)^(1/4)*x).*exp(-x.^2/sqrt(2))*(sqrt(2)/pi)^(1/4)/sqrt(2)))
    legend('n=1')
    xlabel('x')
    disp('norm of the 2nd computed and analytical eigenfunction')
    norm(abs(u(:,2)+sqrt(dx)*hermiteH(1,(2)^(1/4)*x).*exp(-x.^2/sqrt(2))*(sqrt(2)/pi)^(1/4)/sqrt(2)))
    subplot(2,3,3)
    plot(x,abs(u(:,101)- sqrt(dx)*hermiteH(100,(2)^(1/4)*x).*exp(-x.^2/sqrt(2))*(sqrt(2)/pi)^(1/4)/sqrt((2^100*factorial(100)))))
    legend('n=100')
    xlabel('x')
    axes('Position',[0.1 0.49 0.5 0.5],'Xlim',[0 1],'Ylim',[0  1],'Box','off','Visible','off','Units','normalized', 'clipping' , 'off');
    text(0.5, 0.98,'difference between computed and analitic eigenfunctions \alpha=2')
    disp('norm of the 3rd computed and analytical eigenfunction')
    norm(abs(u(:,101)- sqrt(dx)*hermiteH(100,(2)^(1/4)*x).*exp(-x.^2/sqrt(2))*(sqrt(2)/pi)^(1/4)/sqrt((2^100*factorial(100)))))
    subplot(2,3,4)
    plot(x,abs(u(:,1)+ u1(:,1)),'Color','r')
    legend('n=0')
    xlabel('x')
    ylabel('|u_{n}-u1{n}|')
    disp('norm of the 1st FFT and finite difference eigenfunction')
    norm(abs(u(:,1)+ u1(:,1)))
    subplot(2,3,5)
    plot(x,abs(u(:,2)- u1(:,2)),'Color','r')
    legend('n=1')
    xlabel('x')
    disp('norm of the 2nd FFT and finite difference eigenfunction')
    norm(abs(u(:,2)- u1(:,2)))
    subplot(2,3,6)
    plot(x,abs(u(:,101)+ u1(:,101)),'Color','r')
    legend('n=100')
    xlabel('x')
    axes('Position',[0.1 0 0.5 0.5],'Xlim',[0 1],'Ylim',[0  1],'Box','off','Visible','off','Units','normalized', 'clipping' , 'off');
    text(0.5, 0.98,'difference between FFT and Finite Difference eigenfunctions \alpha=2')
    disp('norm of the 3rd FFT and finite difference eigenfunction')
    norm(abs(u(:,101)+ u1(:,101)))
    
end